name: Dev Deploy
on: workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello new change in release ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
